port: "_env:PORT:8080"

database:
  conn-str: "_env:DATABASE_URL:postgres://postgres:postgres@localhost:5432/postgres"
  poolsize: "_env:DATABASE_POOLSIZE:3"

migration-dir: "_env:MIGRATION_DIR:server/mo-nomz/sql/migrations/"
