port: "_env:PORT:8080"

database:
  conn-str: "_env:DATABASE_URL:postgres://postgres:postgres@localhost:5432/postgres"
  poolsize: "_env:DATABASE_POOLSIZE:3"

migration-dir: "_env:MIGRATION_DIR:server/mo-nomz/sql/migrations/"
static-dir: "_env:STATIC_DIR:client/web/public/"
bcrypt-cost: "_env:BCRYPT_COST:4"
cache:
  enabled: "_env:CACHE_ENABLED:false"
  valid-seconds: "_env:CACHE_VALID_SECONDS:604800"
  max-size: "_env:CACHE_MAX_SIZE:10000"
force-ssl: "_env:FORCE_SSL:true"
