on:
  push: {}
  # schedule:
  #   - cron: "0 5 * * *"
jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build
  build-chez:
    if: ${{ github.event_name == 'cron' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/store
            dist-newstyle
          key: cabal-${{ hashFiles('server/chez-grater/chez-grater.cabal') }}
          restore-keys: |
            cabal-${{ hashFiles('server/chez-grater/chez-grater.cabal') }}
            cabal-
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: '8.10.7'
          enable-stack: false
      - run: cabal v2-update
      - run: cabal v2-test chez-grater --test-log /dev/stdout --test-show-details always
  build-server:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/store
            dist-newstyle
          key: cabal-${{ hashFiles('server/mo-nomz/mo-nomz.cabal') }}-${{ hashFiles('server/chez-grater/chez-grater.cabal') }}
          restore-keys: |
            cabal-${{ hashFiles('server/mo-nomz/mo-nomz.cabal') }}-${{ hashFiles('server/chez-grater/chez-grater.cabal') }}
            cabal-${{ hashFiles('server/mo-nomz/mo-nomz.cabal') }}
            cabal-
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: '8.10.4'
          enable-stack: true
      - run: cabal v2-update
      - run: cabal v2-build all
